//! The boot log's parsing, and the distinctions it must not collapse.
//!
//! This log exists because a defect that only appears on real firmware was
//! costing a human a physical boot per hypothesis (testing 34). Its whole value
//! is that a trace can be trusted, so the cases that matter most here are the
//! ones where there is *no* trace: an absent block, an empty block and a boot
//! that did not happen are three different statements, and a reader that blurs
//! them turns missing evidence into a finding.

use rudy_core::boot_log::{parse_env_block, read_boot_log, BootLog};

/// A block as the payload build ships it: header, warning, then padding.
fn block(body: &str) -> String {
    let mut text = String::from("# GRUB Environment Block\n");
    text.push_str("# WARNING: Do not edit this file by tools other than grub-editenv!!!\n");
    text.push_str(body);
    text.push_str(&"#".repeat(256));
    text
}

fn trace_of(log: &BootLog) -> &rudy_core::boot_log::BootTrace {
    match log {
        BootLog::Recorded(trace) => trace,
        other => panic!("expected a recorded trace, got {other:?}"),
    }
}

#[test]
fn a_drive_with_no_block_is_absent_not_a_claim_about_booting() {
    assert_eq!(read_boot_log(None), BootLog::Absent);
}

#[test]
fn a_block_with_no_trace_is_empty_not_a_claim_about_booting() {
    // The payload could not write, or the drive has not been booted. Those look
    // identical from here and neither is "it failed to boot".
    assert_eq!(read_boot_log(Some(&block(""))), BootLog::Empty);
}

#[test]
fn a_trace_set_to_nothing_is_also_empty() {
    assert_eq!(
        read_boot_log(Some(&block("rudy_boot_trace=\n"))),
        BootLog::Empty
    );
}

#[test]
fn the_padding_is_not_read_as_variables() {
    let variables = parse_env_block(&block("rudy_boot_trace=v=1|started=1:2:3\n"));
    assert_eq!(variables.len(), 1);
    assert_eq!(variables["rudy_boot_trace"], "v=1|started=1:2:3");
}

#[test]
fn the_header_lines_are_not_read_as_variables() {
    // The warning line contains no '=', but the header comment convention is
    // what the filter relies on, so both are asserted.
    assert!(parse_env_block(&block("")).is_empty());
}

#[test]
fn the_fields_keep_the_order_they_were_written_in() {
    // The sequence is the evidence: which step was reached before it stopped.
    // A map would sort them and destroy exactly that.
    let log = read_boot_log(Some(&block(
        "rudy_boot_trace=v=1|started=1:2:3|root=hd0,gpt2|ready=1:2:4\n",
    )));
    let names: Vec<&str> = trace_of(&log)
        .fields
        .iter()
        .map(|(name, _)| name.as_str())
        .collect();
    assert_eq!(names, ["v", "started", "root", "ready"]);
}

#[test]
fn a_value_containing_an_equals_sign_survives_intact() {
    // `dev=/dev/disk/by-uuid/...` and the version field both do this.
    let log = read_boot_log(Some(&block(
        "rudy_boot_trace=v=1|dev=/dev/disk/by-label/RUDY\n",
    )));
    assert_eq!(trace_of(&log).get("dev"), Some("/dev/disk/by-label/RUDY"));
}

#[test]
fn the_wait_is_the_gap_between_the_menu_being_ready_and_an_entry_running() {
    // The field the log was built for: it separates a choice a person made from
    // one the machine made.
    let log = read_boot_log(Some(&block(
        "rudy_boot_trace=v=1|ready=10:20:30|entry=x.iso|at=10:20:45\n",
    )));
    assert_eq!(trace_of(&log).seconds_waiting(), Some(15));
}

#[test]
fn a_menu_passed_straight_through_reports_a_zero_wait_not_no_wait() {
    // Zero is the diagnosis. None means "could not measure", and the two must
    // not render the same way.
    let log = read_boot_log(Some(&block(
        "rudy_boot_trace=v=1|ready=10:20:30|entry=x.iso|at=10:20:30\n",
    )));
    assert_eq!(trace_of(&log).seconds_waiting(), Some(0));
}

#[test]
fn grubs_unpadded_clock_fields_parse() {
    // datehook renders second 2 as "2", not "02", so a fixed-offset slice would
    // read this wrong. Observed in the first QEMU run: `ready=13:37:0`.
    let log = read_boot_log(Some(&block(
        "rudy_boot_trace=v=1|ready=13:37:0|entry=x.iso|at=13:37:2\n",
    )));
    assert_eq!(trace_of(&log).seconds_waiting(), Some(2));
}

#[test]
fn a_clock_that_wrapped_past_midnight_is_not_measured() {
    // A negative gap is not a short wait; it is no measurement at all.
    let log = read_boot_log(Some(&block(
        "rudy_boot_trace=v=1|ready=23:59:59|entry=x.iso|at=0:0:5\n",
    )));
    assert_eq!(trace_of(&log).seconds_waiting(), None);
}

#[test]
fn a_nonsense_clock_is_not_measured_rather_than_guessed() {
    for stamp in [
        "25:00:00",
        "10:70:00",
        "10:20:99",
        "10:20",
        "x:y:z",
        "10:20:30:40",
    ] {
        let log = read_boot_log(Some(&block(&format!(
            "rudy_boot_trace=v=1|ready=10:20:30|at={stamp}\n"
        ))));
        assert_eq!(
            trace_of(&log).seconds_waiting(),
            None,
            "{stamp} should not parse as a time"
        );
    }
}

#[test]
fn a_trace_that_stops_before_the_menu_says_so() {
    let log = read_boot_log(Some(&block("rudy_boot_trace=v=1|root=hd0,gpt2\n")));
    let trace = trace_of(&log);
    assert!(!trace.reached_menu());
    assert_eq!(trace.entry(), None);
}

#[test]
fn a_trace_that_reached_the_menu_and_stopped_there_says_that_too() {
    // The menu came up and nothing was chosen — the machine was powered off, or
    // it is still sitting there. Distinct from never reaching the menu.
    let log = read_boot_log(Some(&block("rudy_boot_trace=v=1|ready=1:2:3\n")));
    let trace = trace_of(&log);
    assert!(trace.reached_menu());
    assert_eq!(trace.entry(), None);
    assert_eq!(trace.seconds_waiting(), None);
}

#[test]
fn the_previous_boot_is_kept_alongside_the_current_one() {
    // The drive may be booted twice before anyone reads it.
    let log = read_boot_log(Some(&block(
        "rudy_boot_trace=v=1|ready=2:0:0\nrudy_prev_trace=v=1|ready=1:0:0\n",
    )));
    let trace = trace_of(&log);
    assert_eq!(trace.get("ready"), Some("2:0:0"));
    assert_eq!(trace.previous.as_deref(), Some("v=1|ready=1:0:0"));
}

#[test]
fn an_empty_previous_trace_is_not_reported_as_one() {
    let log = read_boot_log(Some(&block(
        "rudy_boot_trace=v=1|ready=2:0:0\nrudy_prev_trace=\n",
    )));
    assert_eq!(trace_of(&log).previous, None);
}

#[test]
fn the_raw_trace_is_always_carried_so_an_unknown_field_still_arrives() {
    // A future payload will add fields this build does not know. They must not
    // be silently dropped on the way to whoever is reading.
    let raw = "v=1|something_new=42|ready=1:2:3";
    let log = read_boot_log(Some(&block(&format!("rudy_boot_trace={raw}\n"))));
    let trace = trace_of(&log);
    assert_eq!(trace.raw, raw);
    assert_eq!(trace.get("something_new"), Some("42"));
}

#[test]
fn a_field_with_no_value_is_kept_because_reaching_it_is_the_evidence() {
    let log = read_boot_log(Some(&block("rudy_boot_trace=v=1|handoff|ready=1:2:3\n")));
    let trace = trace_of(&log);
    assert_eq!(trace.get("handoff"), Some(""));
}

#[test]
fn the_image_tally_is_counted_rather_than_reported_as_a_flag() {
    // `images=1` on a drive holding three was what the payload used to record:
    // GRUB script has no arithmetic, so its counter is a flag that only says
    // "at least one". A tally of dots is countable here instead.
    let log = read_boot_log(Some(&block("rudy_boot_trace=v=1|images=...|ready=1:2:3\n")));
    assert_eq!(trace_of(&log).image_count(), Some(3));
}

#[test]
fn an_empty_tally_is_no_images_which_is_a_real_answer() {
    // A freshly installed drive nobody has copied anything onto yet. Distinct
    // from a trace that never recorded the field at all.
    let log = read_boot_log(Some(&block("rudy_boot_trace=v=1|images=|ready=1:2:3\n")));
    assert_eq!(trace_of(&log).image_count(), Some(0));
}

#[test]
fn a_trace_without_the_field_reports_no_count_rather_than_zero() {
    let log = read_boot_log(Some(&block("rudy_boot_trace=v=1|ready=1:2:3\n")));
    assert_eq!(trace_of(&log).image_count(), None);
}

#[test]
fn an_old_payloads_numeric_flag_is_not_miscounted_as_a_tally() {
    // Payloads before this change wrote `images=1`. One character, but not a
    // dot — counting its length would report 1 image on a drive holding any
    // number, which is the bug this replaced.
    let log = read_boot_log(Some(&block("rudy_boot_trace=v=1|images=1|ready=1:2:3\n")));
    assert_eq!(trace_of(&log).image_count(), None);
}
