//! The record a drive keeps of its own boot.
//!
//! `CONTEXT.md` §4's boot log, and the only channel out of the one defect that
//! exists on real firmware and on no VM — the machine it was found on has no
//! serial port. So the drive writes down how far it got, onto itself, and
//! `rudy boot-log` reads it back.
//!
//! **The format does not change.** `rudy_core::boot_log` parses it,
//! `boot_signatures.txt` declares the two variable names, and `rudy boot-log`
//! prints it; none of that is touched by the payload underneath changing
//! language. What changes is the path — `/rudy/grub/grubenv` becomes
//! `/rudy/bootlog.env`, because a GRUB-free product does not ship a
//! `/rudy/grub/` directory.
//!
//! Everything here is pure: the block is bytes, and writing it is the firmware
//! half's business. That split is what lets the one behaviour that matters most
//! — a failed write disabling the log — be tested on the bench rather than
//! against a read-only drive.

use alloc::format;
use alloc::string::{String, ToString};
use alloc::vec::Vec;

/// The two lines every GRUB environment block starts with.
///
/// Kept exactly, and not because GRUB is still involved: `grub-editenv` and
/// `rudy_core::boot_log::parse_env_block` both recognise a block by them, and a
/// drive written by this payload has to be readable by the same tools that read
/// a drive written by the last one.
pub const BLOCK_HEADER: &str = "# GRUB Environment Block\n\
     # WARNING: Do not edit this file by tools other than grub-editenv!!!\n";

/// The variable the trace accumulates into.
///
/// From `crates/rudy-core/src/boot_signatures.txt`, which is the source of truth
/// for both names. A rename on either side turns every recorded boot into an
/// absent one, which reads as "this drive has never booted" rather than as "the
/// log moved" — the worst way for a diagnostic to fail. `tests` below checks
/// both against that table.
pub const TRACE_KEY: &str = "rudy_boot_trace";
/// The variable the *previous* boot's trace is carried into.
pub const PREVIOUS_TRACE_KEY: &str = "rudy_prev_trace";

/// The trace format this payload writes.
pub const TRACE_VERSION: &str = "v=1";

/// One boot's trace, accumulated in memory and committed as a whole.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Trace {
    fields: Vec<String>,
    previous: Option<String>,
    /// Whether anything more will be written.
    ///
    /// **A failed write disables the log for the rest of the boot.** Measured
    /// 2026-08-30 against a read-only drive: without this the console filled
    /// with one write error per commit, and fourteen error lines are the very
    /// symptom the log exists to investigate. One is a fault report.
    enabled: bool,
}

impl Trace {
    /// Starts a trace, carrying the previous boot's forward.
    pub fn new(previous: Option<String>, started: &str) -> Self {
        Self {
            fields: alloc::vec![TRACE_VERSION.to_string(), format!("started={started}")],
            previous,
            enabled: true,
        }
    }

    /// A trace on a drive with no block on it: nothing is recorded, and nothing
    /// is ever attempted, so no failure can reach the console.
    pub fn disabled() -> Self {
        Self {
            fields: Vec::new(),
            previous: None,
            enabled: false,
        }
    }

    pub fn is_enabled(&self) -> bool {
        self.enabled
    }

    /// Records one `key=value` field. Ignored once the log is disabled.
    pub fn push(&mut self, field: &str) {
        if self.enabled {
            self.fields.push(field.to_string());
        }
    }

    /// The trace as it would be written.
    pub fn value(&self) -> String {
        self.fields.join("|")
    }

    /// The whole environment block, padded to `size` bytes.
    ///
    /// `None` when the log is disabled, or when the fields no longer fit — a
    /// block whose padding has been eaten is one `grub-editenv` and the parser
    /// would both read wrongly, and a truncated trace is worse than a missing
    /// one because it looks complete.
    pub fn block(&self, size: usize) -> Option<Vec<u8>> {
        if !self.enabled {
            return None;
        }
        let mut text = String::from(BLOCK_HEADER);
        if let Some(previous) = &self.previous {
            text.push_str(&format!("{PREVIOUS_TRACE_KEY}={previous}\n"));
        }
        text.push_str(&format!("{TRACE_KEY}={}\n", self.value()));
        if text.len() > size {
            return None;
        }
        let mut block = text.into_bytes();
        block.resize(size, b'#');
        Some(block)
    }

    /// Records that a write was refused, and stops.
    pub fn disable(&mut self) {
        self.enabled = false;
    }
}

/// The two variables read back out of a block, and nothing else.
///
/// `load_env`'s whitelist form, kept for the reason it was chosen: the block is
/// on a user's drive, and importing every key in it into the payload's own state
/// is a drive deciding what a bootloader's variables are.
pub fn previous_trace(block: &str) -> Option<String> {
    for line in block.lines() {
        if line.starts_with('#') {
            continue;
        }
        let Some((key, value)) = line.split_once('=') else {
            continue;
        };
        if key.trim() == TRACE_KEY && !value.trim_end().is_empty() {
            return Some(value.trim_end().to_string());
        }
    }
    None
}

/// A clock reading as `datehook` rendered one: `H:M:S`, not zero-padded.
///
/// The format is `rudy_core::boot_log::clock_seconds`'s to parse, and it parses
/// numerically rather than by slicing — so this matches what GRUB produced
/// without having to reproduce GRUB's lack of padding on purpose.
pub fn stamp(hour: u8, minute: u8, second: u8) -> String {
    format!("{hour}:{minute}:{second}")
}

/// The tally the menu records instead of a count.
///
/// A count is what this should be and a tally is what it is, because the format
/// is `rudy_core::boot_log::image_count`'s to parse and that function reads
/// dots. GRUB script has no arithmetic, so the payload could only ever say "at
/// least one" — it reported `images=1` on a drive holding three. This payload
/// can count, and writing the count as dots is what keeps the host reader
/// unchanged.
pub fn image_tally(count: usize) -> String {
    // Bounded: `discovery::MAX_IMAGES` already caps what reaches here, and a
    // tally is one byte per image in a block of a few thousand.
    ".".repeat(count.min(crate::discovery::MAX_IMAGES))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The signature table, which is the source of truth for both names.
    const TABLE: &str = include_str!("../../rudy-core/src/boot_signatures.txt");

    fn declared(name: &str) -> String {
        for line in TABLE.lines() {
            let mut fields = line.split('\t');
            if fields.next() != Some("trace") || fields.next() != Some(name) {
                continue;
            }
            return fields
                .next()
                .expect("a trace record carries a name and a variable")
                .to_string();
        }
        panic!("boot_signatures.txt declares no trace variable named {name:?}");
    }

    #[test]
    fn both_variable_names_are_the_ones_the_signature_table_declares() {
        assert_eq!(TRACE_KEY, declared("current"));
        assert_eq!(PREVIOUS_TRACE_KEY, declared("previous"));
    }

    #[test]
    fn a_block_is_exactly_the_size_it_was_given_and_padded_with_hashes() {
        let mut trace = Trace::new(None, "1:2:3");
        trace.push("root=hd0");
        let block = trace.block(8192).expect("a block is produced");
        assert_eq!(block.len(), 8192);
        assert_eq!(block[block.len() - 1], b'#');
    }

    #[test]
    fn the_block_starts_with_the_two_lines_every_reader_recognises() {
        let block = Trace::new(None, "1:2:3").block(8192).expect("a block");
        let text = String::from_utf8(block).expect("the block is text");
        assert!(text.starts_with(BLOCK_HEADER), "{:?}", &text[..80]);
    }

    #[test]
    fn the_trace_is_pipe_separated_and_starts_with_the_version() {
        let mut trace = Trace::new(None, "9:8:7");
        trace.push("root=hd0");
        trace.push("data=hd0,gpt1");
        assert_eq!(trace.value(), "v=1|started=9:8:7|root=hd0|data=hd0,gpt1");
    }

    /// The previous boot's trace is carried forward, which is what makes a
    /// drive that failed twice tell you about both.
    #[test]
    fn the_previous_trace_is_carried_into_the_new_block() {
        let trace = Trace::new(Some(String::from("v=1|started=1:1:1")), "2:2:2");
        let text = String::from_utf8(trace.block(8192).expect("a block")).expect("text");
        assert!(text.contains("rudy_prev_trace=v=1|started=1:1:1\n"));
        assert!(text.contains("rudy_boot_trace=v=1|started=2:2:2\n"));
    }

    /// Only the current trace is read back out of a block a user's drive
    /// carries, and it becomes the *previous* one for the boot that follows.
    #[test]
    fn only_the_current_trace_is_read_back_out_of_a_block() {
        let block = "# GRUB Environment Block\n\
                     # WARNING: Do not edit this file by tools other than grub-editenv!!!\n\
                     rudy_prev_trace=v=1|started=0:0:0\n\
                     rudy_boot_trace=v=1|started=1:1:1|ready=1:1:5\n\
                     somebody_elses_variable=do not import this\n\
                     ####################\n";
        assert_eq!(
            previous_trace(block).as_deref(),
            Some("v=1|started=1:1:1|ready=1:1:5")
        );
    }

    #[test]
    fn an_empty_trace_in_a_block_is_not_a_previous_boot() {
        let block = "# GRUB Environment Block\nrudy_boot_trace=\n####\n";
        assert_eq!(previous_trace(block), None);
    }

    /// The regression the console-full-of-errors measurement produced.
    #[test]
    fn a_disabled_log_produces_no_block_and_accepts_no_more_fields() {
        let mut trace = Trace::new(None, "1:2:3");
        trace.disable();
        trace.push("layout=archiso");
        assert_eq!(trace.block(8192), None);
        assert!(!trace.is_enabled());
        assert_eq!(trace.value(), "v=1|started=1:2:3");
    }

    #[test]
    fn a_drive_with_no_block_never_attempts_a_write() {
        let trace = Trace::disabled();
        assert!(!trace.is_enabled());
        assert_eq!(trace.block(8192), None);
    }

    /// A trace longer than the block it must fit in is refused rather than
    /// truncated: a truncated trace looks complete and is not.
    #[test]
    fn a_trace_too_long_for_its_block_is_refused_rather_than_cut() {
        let mut trace = Trace::new(None, "1:2:3");
        for index in 0..500 {
            trace.push(&format!("entry=a-very-long-image-name-{index:04}.iso"));
        }
        assert_eq!(trace.block(8192), None);
        assert!(trace.block(64 * 1024).is_some());
    }

    #[test]
    fn a_stamp_is_rendered_the_way_datehook_rendered_one() {
        assert_eq!(stamp(1, 2, 3), "1:2:3");
        assert_eq!(stamp(23, 59, 59), "23:59:59");
    }

    /// `image_count` in `rudy-core` reads dots, and `Some(0)` — a drive with no
    /// images yet — is a real answer distinct from a field that was never
    /// written.
    #[test]
    fn the_image_tally_is_one_dot_per_image() {
        assert_eq!(image_tally(0), "");
        assert_eq!(image_tally(3), "...");
        assert_eq!(image_tally(usize::MAX).len(), crate::discovery::MAX_IMAGES);
    }
}
